#include <iostream>
#include "nums.hh"
#include "tk.hh"
#include "nv.hh"
#include "modlab.h"
using namespace std;
void Ldistr::distr(double *py,double *pdydt) {
	double NOL=0.;
	setiso(py); setdiso(pdydt);
	for (int i=0;i<Nn;i++) pdydt[i]=0.;
	h6.sett(); t3.sett(); s7.sett(); p5.sett(); e4.sett(); 
	Problem.f(py,pdydt);
	Problem.ff(py,pdydt);
	Problem.fin(py);/**/
	double xthf=thft-cthf.sumt();
//h6.coriso(py[nh6],h6.sumt()); fbp.coriso(py[nfbp],fbp.sumt()); t3.coriso(py[nt3],t3.sumt()); pep.coriso(py[npep],pep.sumt()); pyr.coriso(py[npyr],pyr.sumt()); pyrm.coriso(py[npyrm],pyrm.sumt()); coa.coriso(py[ncoa],coa.sumt()); oa.coriso(py[noa],oa.sumt()); oac.coriso(py[noac],oac.sumt()); cit.coriso(py[ncit],cit.sumt()); citc.coriso(py[ncitc],citc.sumt()); akg.coriso(py[nakg],akg.sumt()); akgc.coriso(py[nakgc],akgc.sumt()); fum.coriso(py[nfum],fum.sumt()); mal.coriso(py[nmal],mal.sumt()); 
gl.input(h6,fluxes[hk]/gl.sumt(), 0.);
glycog.input(h6,fluxes[glycogout], fluxes[glycogin]);
h6.input(fbp,fluxes[pfk], fluxes[fbpase]);
t3.input(pep,fluxes[t3pep], fluxes[pept3]);
pep.input(pyr,fluxes[pk], 0.);
pyr.input(lac,fluxes[pyrlac], fluxes[lacpyr]);
pyr.input(pyrm,fluxes[pyrdcm], fluxes[pyrdmc]);
pyrm.cutfirst(coa,fluxes[pdh]);
cit.icdh(akg,fluxes[citakg]);
akg.decarb(fum,fluxes[akgfum]);
fum.input(mal,fluxes[fumal], fluxes[malfum]);
fum.output(fluxes[fumout]);
mal.input(oa,fluxes[maloa], fluxes[oamal]);
pyrm.carb(oa,fluxes[pc]);
mal.decarb(pyrm,fluxes[malicm]);
oac.decarb(pyr,fluxes[malicc]);
oa.decarb(pep,fluxes[pepck]);
h6.cutfirst(p5,fluxes[ppp]);
oac.input(mal,fluxes[oacd], fluxes[mald]);
cit.input(citc,fluxes[citdmc], fluxes[citdcm]);
akg.input(akgc,fluxes[akgdmc], fluxes[akgdcm]);
citc.liase(oac,coac,fluxes[coaout]);
coac.input(coa,fluxes[coar],0.);
citc.icdh(akgc,fluxes[citakg1]);
akgc.icdhr(citc,fluxes[akgcit1]);
gln.input(akgc,fluxes[gln_in], fluxes[gln_out]);
gln.output(fluxes[gln_pr]);
glu.input(akgc,fluxes[gluin], fluxes[gluout]);
t3.input(ser,fluxes[t3ser], 0.);
t3.input(agl,fluxes[aglout], fluxes[aglin]);
ser.input(pyrm,fluxes[serpyr], 0.);
ser.output(fluxes[ser_pr]);
ser_gly (fluxes[sergly],xthf);
gly_ser(fluxes[glyser]);
cthf.output(fluxes[thf]);
cthf.iso[0]+=(fluxes[mthf]*xthf);
oac.input(asp,fluxes[asp_o], fluxes[asp_i]);
//asp.output(fluxes[asp_pr]);
fum.diso[0]+=fluxes[asp_i];
t3.input(ala,fluxes[ala_o], 0);
pyr.input(ala,0, fluxes[ala_i]);
ala.diso[0]+=fluxes[trpala];
//ala.output(fluxes[ala_pr]);
p5.input(rna,fluxes[r5_o], fluxes[r5_i]);
pyr.diso[0]+=fluxes[cystin];
pro.input(akgc,fluxes[proin], fluxes[proout]);
pro.output(fluxes[pro_pr]);
akg.diso[0]+=fluxes[kgin];
coa.diso[0]+=fluxes[coain];
csyn(coa.iso,coa.diso,oa.iso,oa.diso,cit.diso,fluxes[cs0]);
split(fbp.iso,fbp.diso,t3.iso,t3.diso,fluxes[aldf],fluxes[aldf+1]);
spInvsl(fbp.iso,fbp.diso,t3.iso,t3.diso,fluxes[aldf+2],t3.sumt());
	h6.tka(t3,e4,s7,fluxes[tafl]);
	s7.tka(e4,t3,h6,fluxes[tafl+1]);
	h6.invista(t3,fluxes[tafl+2]);
	s7.invista(e4,fluxes[tafl+3]);
p5.tkk(t3,p5,s7,fluxes[tkfl]);
s7.tkk(p5,t3,p5,fluxes[tkfl+1]);
h6.tkk(e4,t3,p5,fluxes[tkfl+2]);
p5.tkk(t3,e4,h6,fluxes[tkfl+3]);
h6.tkk(e4,p5,s7,fluxes[tkfl+4]);
s7.tkk(p5,e4,h6,fluxes[tkfl+5]);
p5.invistk(t3,fluxes[tkfl+6]);
h6.invistk(e4,fluxes[tkfl+7]);
s7.invistk(p5,fluxes[tkfl+8]);
	gl.volume(Vt);
	lac.volume(Vt);
	glu.volume(Vt);
	gln.volume(Vt);
//	ala.volume(Vt);
	ser.volume(Vt);
	agl.volume(Vt);
	gly.volume(Vt);
	rna.volume(Vi);
//	asp.volume(Vt);
	pro.volume(Vt);
	symm(fum.getisot());
xx[nh6]=h6.sumt(); xx[nfbp]=fbp.sumt(); xx[nt3]=t3.sumt(); xx[npep]=pep.sumt(); xx[npyr]=pyr.sumt(); xx[npyrm]=pyrm.sumt(); xx[ncoa]=coa.sumt(); xx[noa]=oa.sumt(); xx[noac]=oac.sumt(); xx[ncit]=cit.sumt(); xx[ncitc]=citc.sumt(); xx[nakg]=akg.sumt(); xx[nakgc]=akgc.sumt(); xx[nfum]=fum.sumt(); xx[nmal]=mal.sumt(); xx[np5]=p5.sumt(); xx[ne4]=e4.sumt(); xx[ns7]=s7.sumt();
xx[ngl]=py[ngl]=gl.sumt(); xx[nlac]=py[nlac]=lac.sumt(); xx[nglu]=py[nglu]=glu.sumt();  xx[ngln]=py[ngln]=gln.sumt();  xx[nala]=py[nala]=ala.sumt();  xx[nser]=py[nser]=ser.sumt(); xx[nrna]=py[nrna]=rna.sumt();  xx[nasp]=py[nasp]=asp.sumt();  xx[npro]=py[npro]=pro.sumt();   xx[ngly]=py[ngly]; 
}
